import type { RoleDefinition, RoleKey } from './types';

export const ROLE_CATALOG: Record<RoleKey, RoleDefinition> = {
  VILLAGER: {
    key: 'VILLAGER',
    name: 'Villager',
    faction: 'VILLAGE',
    power: 1,
    summary: 'Find and eliminate every Werewolf.',
  },
  WEREWOLF: {
    key: 'WEREWOLF',
    name: 'Werewolf',
    faction: 'WEREWOLF',
    power: -5,
    summary: 'Coordinate with the pack and reach parity.',
    actionKind: 'WOLF_VOTE',
  },
  SEER: {
    key: 'SEER',
    name: 'Seer',
    faction: 'VILLAGE',
    power: 3,
    summary: 'Inspect one living player each night and learn their exact role.',
    actionKind: 'INVESTIGATE',
    unique: true,
  },
  BODYGUARD: {
    key: 'BODYGUARD',
    name: 'Bodyguard',
    faction: 'VILLAGE',
    power: 2,
    summary: 'Protect one other living player from one pack attack each night. Protection does not stop a Hunter shot.',
    actionKind: 'PROTECT',
    unique: true,
  },
  HUNTER: {
    key: 'HUNTER',
    name: 'Hunter',
    faction: 'VILLAGE',
    power: 1,
    summary: 'Take one living player with you when eliminated.',
    actionKind: 'HUNTER_SHOT',
    unique: true,
  },
  MASON: {
    key: 'MASON',
    name: 'Mason',
    faction: 'VILLAGE',
    power: 1,
    summary: 'Know the other Masons and coordinate in a private room.',
    minimumCount: 2,
  },
  APPRENTICE_SEER: {
    key: 'APPRENTICE_SEER',
    name: 'Apprentice Seer',
    faction: 'VILLAGE',
    power: 2,
    summary: 'When the Seer is eliminated, inherit their investigations and inspect one living player each night.',
    actionKind: 'INVESTIGATE',
    unique: true,
  },
  MAYOR: {
    key: 'MAYOR',
    name: 'Mayor',
    faction: 'VILLAGE',
    power: 2,
    summary: 'Your vote counts twice in Day and Final ballots.',
    unique: true,
  },
  CUPID: {
    key: 'CUPID',
    name: 'Cupid',
    faction: 'VILLAGE',
    power: 1,
    summary: 'Choose two living players once, including yourself. If either is eliminated, their lover is eliminated too.',
    actionKind: 'CUPID_PAIR',
    unique: true,
  },
};
